// Generated by CoffeeScript 1.10.0
(function() {
  var GLProgramFactory;

  module.exports = GLProgramFactory = (function() {
    function GLProgramFactory() {
      console.log("hello");
    }

    GLProgramFactory.prototype.constructShader = function(GL, source, type) {
      var shader;
      shader = GL.createShader(type);
      GL.shaderSource(shader, source);
      GL.compileShader(shader);
      if (!GL.getShaderParameter(shader, GL.COMPILE_STATUS)) {
        console.log("Failed to compiled Shader.");
        console.log(GL);
        console.log(source);
        console.log(type);
        return null;
      }
      return shader;
    };

    GLProgramFactory.prototype.constructProgramFromShaders = function(GL, __vert, __frag) {
      var program;
      program = GL.createProgram();
      GL.attachShader(program, __vert);
      GL.attachShader(program, __frag);
      GL.linkProgram(program);
      GL.validateProgram(program);
      console.log(GL.getProgramInfoLog(program));
      console.log(GL.getProgramParameter(program, GL.VALIDATE_STATUS));
      console.log("^^");
      return program;
    };

    GLProgramFactory.prototype.constructProgramFromSources = function(GL, __vert, __frag) {
      var fragshader, vertshader;
      vertshader = this.constructShader(GL, __vert, GL.VERTEX_SHADER);
      fragshader = this.constructShader(GL, __frag, GL.FRAGMENT_SHADER);
      return this.constructProgramFromShaders(GL, vertshader, fragshader);
    };

    return GLProgramFactory;

  })();

}).call(this);
