// Generated by CoffeeScript 1.10.0
(function() {
  var ShaderReader;

  module.exports = ShaderReader = (function() {
    function ShaderReader(id) {
      var error, error1, shader;
      try {
        shader = document.getElementById(id);
        this.shaderSource = shader.getAttribute("shader_text");
        this.success = true;
      } catch (error1) {
        error = error1;
        console.log(error);
        this.success = false;
      }
    }

    ShaderReader.prototype.didSucced = function() {
      return this.success;
    };

    ShaderReader.prototype.toString = function() {
      if (this.didSucced()) {
        return this.shaderSource;
      }
      return null;
    };

    return ShaderReader;

  })();

}).call(this);
