// Generated by CoffeeScript 1.10.0
(function() {
  var Emitter;

  module.exports = Emitter = (function() {
    function Emitter() {
      this.EventCallbacks = {
        "null": []
      };
    }

    Emitter.prototype.emit = function(event) {
      var callback, i, len, ref, results;
      ref = this.EventCallbacks[event];
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        callback = ref[i];
        results.push(callback(event));
      }
      return results;
    };

    Emitter.prototype.subscribe = function(event, callback) {
      return this.EventCallbacks[event].push(event);
    };

    return Emitter;

  })();

}).call(this);
