// Generated by CoffeeScript 1.10.0
(function() {
  var sizes, toggleFullscreen;

  sizes = {};

  toggleFullscreen = function(elem, callback) {
    var cond, name;
    if (callback == null) {
      callback = function(e) {};
    }
    name = "" + elem;
    cond = (document.fullScreenElement != null) || (document.msFullscreenElement != null) || (document.mozFullScreen != null) || (document.webkitIsFullScreen != null);
    if (cond) {
      sizes[elem] = elem.width;
      sizes[elem] = elem.height;
      if (elem.requestFullScreen) {
        elem.requestFullScreen();
      }
      if (elem.mozRequestFullScreen) {
        elem.mozRequestFullScreen();
      }
      if (elem.webkitRequestFullScreen) {
        elem.webkitRequestFullScreen();
      }
      if (elem.msRequestFullscreen) {
        elem.msRequestfullscreen();
      }
      elem.style.width = "100vw";
      elem.style.height = "100vh";
      elem.style.padding = "40px 15px";
      console.log(elem.style.width + " , " + elem.style.height);
      return console.log(elem);
    }
  };

  window["toggleFullscreen"] = toggleFullscreen;

}).call(this);
